apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: event-store
  name: event-store
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yml convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: event-store
    spec:
      containers:
      - env:
        - name: EVENT_STORE_MAX_WORKERS
          value: "100"
        - name: EVENT_STORE_REDIS_HOST
          value: redis
        image: eu.gcr.io/central-beach-194106/ordershop/event-store:latest
        name: event-store
        resources: {}
      restartPolicy: Always
status: {}
