apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: message-queue
  name: message-queue
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: message-queue
    spec:
      containers:
      - env:
        - name: MESSAGE_QUEUE_MAX_WORKERS
          value: "100"
        - name: MESSAGE_QUEUE_REDIS_HOST
          value: redis
        image: eu.gcr.io/central-beach-194106/message-queue:latest
        name: message-queue
        resources: {}
      restartPolicy: Always
status: {}
