apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: read-model
  name: read-model
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yml convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: read-model
    spec:
      containers:
      - env:
        - name: EVENT_STORE_HOSTNAME
          value: event-store
        - name: MESSAGE_QUEUE_HOSTNAME
          value: message-queue
        image: eu.gcr.io/central-beach-194106/ordershop/read-model:latest
        name: read-model
        resources: {}
      restartPolicy: Always
status: {}
