apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: shipping-service
  name: shipping-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yml convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: shipping-service
    spec:
      containers:
      - env:
        - name: EVENT_STORE_HOSTNAME
          value: event-store
        - name: MESSAGE_QUEUE_HOSTNAME
          value: message-queue
        image: martinforstner/ordershop/shipping-serivce:latest
        name: shipping-service
        resources: {}
      restartPolicy: Always
status: {}
